#!/bin/bash

# 1
# Print Statments 
echo "Hello ACM"



# 2
# Calculate a+b
a=1
b=3

echo $a+$b=$((a+b))



# 3
# taking inputs 
read -p "What is your name? " name
# ^
# | echo "What is your name?"
# | read name

echo "Hello, $name!"



# 4
club=ACM

# Append to File
printf "Hello!
" >> test.md
printf "Club Name = $club" >> test.md

# Write to File
read -p "Replace test.md contents with: " new_content
printf $new_content > test.md

# Remove File After Any Key Press
read -n 1
rm test.md



# 5
# Conditional Statement
a=123
b=321

if [[ $(whoami) != 'gev' ]]; then
    echo "No bueno"
elif [ $a -gt $b ]; then
	echo "$a > $b"
elif [ $a -lt $b ]; then
	echo "$a < $b"
else
	echo "$a == $b"
fi



# 6
# While Loop
a=1
b=5

while [ $a -lt $b ]; do
	echo "$a < $b -> a=$a+1"
	a=$((a+1))
done



# 7
# For Loop
names=('cat' 'dog' 'horse')

for name in ${names[@]}; do
    echo $name
done